version: "3.8"

services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: sgtech_mysql
    restart: always
    environment:
      MYSQL_DATABASE: sgtech_db
      MYSQL_USER: sgtech_user
      MYSQL_PASSWORD: AxrA6eRhcEY7X6e6eZxMQeMG9
      MYSQL_ROOT_PASSWORD: root_password_change_me
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-config.cnf:/etc/mysql/conf.d/custom.cnf:ro
    networks:
      - wordpress_network
    ports:
      - "3306:3306"
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode=NO_ENGINE_SUBSTITUTION
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgtech_wordpress
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: sgtech_db
      WORDPRESS_DB_USER: sgtech_user
      WORDPRESS_DB_PASSWORD: AxrA6eRhcEY7X6e6eZxMQeMG9
    volumes:
      - ./:/var/www/html
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge

volumes:
  db_data:
